services:
  - type: web
    name: socialrise-x-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    nodeVersion: 16.x
    buildFilter:
      paths:
        - src/**/*.js
        - src/**/*.jsx
        - src/**/*.css
        - public/**/*
        - package*.json
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: CI
        value: false