services:
  - type: web
    name: socialrise-x-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.json
        name: Content-Type
        value: application/json
      - path: /*.png
        name: Content-Type
        value: image/png
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
      - type: rewrite
        source: /register
        destination: /index.html
      - type: rewrite
        source: /login
        destination: /index.html
      - type: rewrite
        source: /app/*
        destination: /index.html
      - type: rewrite
        source: /admin/*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://socialrisexbackend.onrender.com/api
      - key: NODE_ENV
        value: production
      - key: CI
        value: false