services:
  - type: web
    name: socialrisex
    buildCommand: npm install && npm run build
    startCommand: npm run start
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html