services:
  - type: web
    name: socialrise-x-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://socialrisex.vercel.app/  # Update this line
